---
title: "fig02_differenceinmeans"
author: "Brendon Krall"
date: "2022-09-01"
output: html_document
---

# Difference in Means of Vote Share PML Summary Table
```{r, message=FALSE, echo=False}
# Summarize and save as a table to graph 
pml_table <- df_02_08 %>% 
  filter((Year == 2002 | 2008), `Party Initials` == 'PML') %>%
  group_by(Year,`Treated before 2008 elections`) %>%
  summarize(
    'Percentage of Vote Share' = mean(Vote_Share.1)
)

# Reshape the table to wide format
pml_table <- spread(pml_table, key = "Treated before 2008 elections", value = 'Percentage of Vote Share')

# Transpose the table, remove the first row, and save as df object
pml_table <- t(pml_table)
pml_table <- pml_table[-1,]
pml_table <- as.data.frame(pml_table)

# Create a difference column
pml_table <- pml_table %>%
  mutate(
    Difference = pml_table$V2 - pml_table$V1
)

# Rename columns and rows
colnames(pml_table) <- c(2002, 2008, 'Difference')
rownames(pml_table) <- c("Unvisited Districts", "Visited Districts")

print(pml_table)
```


# Difference in Means of Vote Share PML-N
```{r, message=FALSE, echo=False}
pmln_table <- df_02_08 %>% 
  filter((Year == 2002 | 2008), `Party Initials` == 'PML-N') %>%
  group_by(Year,`Treated before 2008 elections`) %>%
  summarize(
    'Percentage of Vote Share' = mean(Vote_Share.1)
)

# Reshape the table to wide format
pmln_table <- spread(pmln_table, key = "Treated before 2008 elections", value = 'Percentage of Vote Share')

# Transpose the table, remove the first row, and save as df object
pmln_table <- t(pmln_table)
pmln_table <- pmln_table[-1,]
pmln_table <- as.data.frame(pmln_table)

# Create a difference column
pmln_table <- pmln_table %>%
  mutate(
    Difference = pmln_table$V2 - pmln_table$V1
)

# Rename columns and rows
colnames(pmln_table) <- c(2002, 2008, 'Difference')
rownames(pmln_table) <- c("Unvisited Districts", "Visited Districts")

print(pmln_table)
```


# Difference in Means of Vote Share PPPP
```{r, message=FALSE, echo=False}
pppp_table <- df_02_08 %>% 
  filter((Year == 2002 | 2008), `Party Initials` == 'PPPP') %>%
  group_by(Year,`Treated before 2008 elections`) %>%
  summarize(
    'Percentage of Vote Share' = mean(Vote_Share.1)
)

# Reshape the table to wide format
pppp_table <- spread(pppp_table, key = "Treated before 2008 elections", value = 'Percentage of Vote Share')

# Transpose the table, remove the first row, and save as df object
pppp_table <- t(pppp_table)
pppp_table <- pppp_table[-1,]
pppp_table <- as.data.frame(pppp_table)

# Create a difference column
pppp_table <- pppp_table %>%
  mutate(
    Difference = pppp_table$V2 - pppp_table$V1
)

# Rename columns and rows
colnames(pppp_table) <- c(2002, 2008, 'Difference')
rownames(pppp_table) <- c("Unvisited Districts", "Visited Districts")

print(pppp_table)
```
