---
title: "RoL Election Analysis"
author: "Brendon Krall"
date: "8/8/2022"
output: html_document
---

# Perform Regression Analysis - PML
```{r, echo=False}
# OLS 
reg_pml <- lm(Vote_Share.1 ~ treated, data = df_pml)
# cluster-robust SEs for reg_pml
cl.cov.pml1 <- cluster.vcov(reg_pml, df_pml$`PA ID`) 
cl.robust.se.pml1 <- sqrt(diag(cl.cov.pml1))

# OLS with 'count' variable control
reg_pml2 <- lm(Vote_Share.1 ~ treated + year_dummy, data = df_pml)
# cluster-robust SEs for reg_pml2
cl.cov.pml2 <- cluster.vcov(reg_pml2, df_pml$`PA ID`) 
cl.robust.se.pml2 <- sqrt(diag(cl.cov.pml2))

# OLS with TWFE 
reg_pml3 <- lm(Vote_Share.1 ~ treated + year_dummy + constituency_dummy, data = df_pml)
# cluster-robust SEs for reg_pml3
cl.cov.pml3 <- cluster.vcov(reg_pml3, df_pml$`PA ID`) 
cl.robust.se.pml3 <- sqrt(diag(cl.cov.pml3))

# OLS with TWFE + 'count' control variable 
reg_pml4 <- lm(Vote_Share.1 ~ treated + year_dummy + constituency_dummy + count, data = df_pml)
# cluster-robust SEs for reg_pml4
cl.cov.pml4 <- cluster.vcov(reg_pml4, df_pml$`PA ID`) 
cl.robust.se.pml4 <- sqrt(diag(cl.cov.pml4))

table02_DiDregression <- stargazer(reg_pml,reg_pml2,reg_pml3,reg_pml4, type="text", title="Effect of CJ visits on vote share for General Musharraf PML - Impact on Dicator’s Party", keep = c('Constant','treated', 'year_dummy2008', 'count'), order=c('Constant','treated'), covariate.labels=c('Unvisited Districts', 'Visited Districts','Year Dummy (2008)', 'Controls'), column.labels=c('OLS', 'OLS w/ Year FE', 'TWFE', 'TWFE w/ Controls'), dep.var.caption = '', dep.var.labels.include = FALSE, se = list(cl.robust.se.pml1, cl.robust.se.pml2, cl.robust.se.pml3, cl.robust.se.pml4), notes = c("Robust standard errors appear in brackets (clustered at the district level).",  "The table presents DiD estimation of the effect of Chief Justice visits to districts of", "Pakistan before 2008 elections on the share of votes in favour of PML party in 2008 provincial", "and national elections (compare to 2002 elections). Outcome variable is visit to a given",  "district. Controls include: # of candidates in a district (count)."), notes.align = "l", keep.stat=c('n', 'adj.rsq', 'f'), add.lines = list("Mean" = c("Mean", round(mean(df_pml$Vote_Share.1), 2), round(mean(df_pml$Vote_Share.1), 2), round(mean(df_pml$Vote_Share.1), 2), round(mean(df_pml$Vote_Share.1), 2))))
```

# Perform Regression Analysis for Opposition 
```{r, echo=False}
## PML-N
# OLS with TWFE 
reg_pmln3 <- lm(Vote_Share.1 ~ treated + year_dummy + constituency_dummy, data = df_pml_n)
# cluster-robust SEs for reg_pmln3
cl.cov.pmln3 <- cluster.vcov(reg_pmln3, df_pml_n$`PA ID`) 
cl.robust.se.pmln3 <- sqrt(diag(cl.cov.pmln3))

# OLS with TWFE + 'count' control variable 
reg_pmln4 <- lm(Vote_Share.1 ~ treated + year_dummy + constituency_dummy + count, data = df_pml_n)
# cluster-robust SEs for reg_pmln4
cl.cov.pmln4 <- cluster.vcov(reg_pmln4, df_pml_n$`PA ID`) 
cl.robust.se.pmln4 <- sqrt(diag(cl.cov.pmln4))

## PPP
# OLS with TWFE 
reg_pppp3 <- lm(Vote_Share.1 ~ treated + year_dummy + constituency_dummy, data = df_pppp)
# cluster-robust SEs for reg_pppp3
cl.cov.pppp3 <- cluster.vcov(reg_pppp3, df_pppp$`PA ID`) 
cl.robust.se.pppp3 <- sqrt(diag(cl.cov.pppp3))

# OLS with TWFE + 'count' control variable 
reg_pppp4 <- lm(Vote_Share.1 ~ treated + year_dummy + constituency_dummy + count, data = df_pppp)
# cluster-robust SEs for reg_pppp4
cl.cov.pppp4 <- cluster.vcov(reg_pppp4, df_pppp$`PA ID`) 
cl.robust.se.pppp4 <- sqrt(diag(cl.cov.pppp4))

# Create Opposition (PML-N and PPP) Regression Table
table03_DiDregressionOpp <- stargazer(reg_pmln3,reg_pmln4,reg_pppp3,reg_pppp4, type="text", title="Effect of CJ visits on vote share for the Opposition (PML-N & PPP)", keep = c('Constant','treated', 'count', 'year_dummy2008'), order=c('Constant','treated'), covariate.labels=c('Unvisited Districts', 'Visited Districts', 'Year Dummy (2008)', 'Controls'), column.labels=c('PML-N: TWFE', 'PML-N: TWFE w/ Controls', 'PPP: TWFE', 'PPP: TWFE w/ Controls'), dep.var.caption = '', dep.var.labels.include = FALSE, se = list(cl.robust.se.pmln3, cl.robust.se.pmln4, cl.robust.se.pppp3, cl.robust.se.pppp4), notes = c("Robust standard errors appear in brackets (clustered at the district level).",  "The table presents DiD estimation of the effect of Chief Justice visits to districts of", "Pakistan before 2008 elections on the share of votes in favour of opposition parties in 2008", "provincial and national elections (compare to 2002 elections). Outcome variable is visit to a",  "given district. Controls include: # of candidates in a district (count)."), notes.align = "l", keep.stat=c('n', 'adj.rsq', 'f'), add.lines = list("Mean" = c("Mean", round(mean(df_pml_n$Vote_Share.1), 2), round(mean(df_pml_n$Vote_Share.1), 2), round(mean(df_pppp$Vote_Share.1), 2), round(mean(df_pppp$Vote_Share.1), 2))))
```

# Construct Bar Graph Variables 
```{r, echo=False}
df_02_08_bargraphs <- df_02_08 %>%
# Filter for specific political parties of interest
  filter(`Party Initials` %in% c('PML', 'PML-N', 'PPPP')) %>%
# Calculate summary statistics used to build confidence intervals 
  group_by(`Party Initials`, Year, `Treated before 2008 elections`) %>%
  summarise( 
    n=n(),
    mean=mean(Vote_Share.1),
    sd=sd(Vote_Share.1)) %>%
  mutate(se=sd/sqrt(n),
         ic=(se * qt((1-0.05)/2 + .5, n-1))) %>%
# Rename column name and binary variable dummys to characters 
  rename(group = 'Treated before 2008 elections') 

df_02_08_bargraphs$group <- ifelse(df_02_08_bargraphs$group == 1, 'Visited', 'Never Visited')
```

# Bar Chart of Vote Share PML
```{r, echo=False}
# Subset data for PML
pml_bar <- df_02_08_bargraphs %>%
  filter(`Party Initials` == 'PML')

# Create bar chart for PML 
fig01_bargraphPML <- ggplot(data = pml_bar, aes(x=factor(Year), y=mean, groups=group, fill=group)) +
  geom_bar(colour='black', width=0.50, stat='identity', position=position_dodge(0.5)) + 
  geom_errorbar(aes(x=factor(Year), ymin=mean-ic, ymax=mean+ic), width=0.25, colour="#778899", alpha=1, size=1, position=position_dodge(0.5)) +
  ggtitle('Impact of CJ visits on General Musharraf’s Party - PML') + 
  labs(y= "Vote Share (%)", x = '', caption = str_wrap('Note: The figure presents the effect of Chief Justice visits to districts of Pakistan before 2008 elections on the share of votes in # favor of the PML party in 2008 provincial and national elections (compared to 2002 elections). The vertical lines reflect the 95% confidence intervals.')) +
  theme_light() + 
  theme(legend.position="right", legend.title=element_blank(), plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual("group", values = c("Visited" = "#2F4F4F", "Never Visited" = "#DCDCDC"))

print(fig01_bargraphPML)
```

# Difference in Means of Vote Share PML Summary Table
```{r, message=FALSE, echo=False}
# Summarize and save as a table to graph 
pml_table <- df_02_08 %>% 
  filter((Year == 2002 | 2008), `Party Initials` == 'PML') %>%
  group_by(Year,`Treated before 2008 elections`) %>%
  summarize(
    'Percentage of Vote Share' = mean(Vote_Share.1)
)

# Reshape the table to wide format
pml_table <- spread(pml_table, key = "Treated before 2008 elections", value = 'Percentage of Vote Share')

# Transpose the table, remove the first row, and save as df object
pml_table <- t(pml_table)
pml_table <- pml_table[-1,]
pml_table <- as.data.frame(pml_table)

# Create a difference column
pml_table <- pml_table %>%
  mutate(
    Difference = pml_table$V2 - pml_table$V1
)

# Rename columns and rows
colnames(pml_table) <- c(2002, 2008, 'Difference')
rownames(pml_table) <- c("Unvisited Districts", "Visited Districts")

print(pml_table)
```

# Bar Chart of Vote Share PML-N
```{r, echo=False}
# Subset data for PML
pmln_bar <- df_02_08_bargraphs %>%
  filter(`Party Initials` == 'PML-N')

# Create bar chart for PML 
fig02_bargraphPMLN <- ggplot(data = pmln_bar, aes(x=factor(Year), y=mean, groups=group, fill=group)) +
  geom_bar(colour='black', width=0.50, stat='identity', position=position_dodge(0.5)) + 
  geom_errorbar(aes(x=factor(Year), ymin=mean-ic, ymax=mean+ic), width=0.25, colour="#778899", alpha=1, size=1, position=position_dodge(0.5)) +
  ggtitle('Impact of CJ visits on Party Pledging Support for Lawyers Movment - PML-N') + 
  labs(y= "Vote Share (%)", x = '', caption=str_wrap('Note: The figure presents the effect of Chief Justice visits to districts of Pakistan before 2008 elections on the share of votes in # favor of PML-N party in 2008 provincial and national elections (compare to 2002 elections). The vertical lines reflect the 95% confidence intervals.')) +
  theme_light() + 
  theme(legend.position="right", legend.title=element_blank(), plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual("group", values = c("Visited" = "#2F4F4F", "Never Visited" = "#DCDCDC"))

print(fig02_bargraphPMLN)
```

# Difference in Means of Vote Share PML-N
```{r, message=FALSE, echo=False}
pmln_table <- df_02_08 %>% 
  filter((Year == 2002 | 2008), `Party Initials` == 'PML-N') %>%
  group_by(Year,`Treated before 2008 elections`) %>%
  summarize(
    'Percentage of Vote Share' = mean(Vote_Share.1)
)

# Reshape the table to wide format
pmln_table <- spread(pmln_table, key = "Treated before 2008 elections", value = 'Percentage of Vote Share')

# Transpose the table, remove the first row, and save as df object
pmln_table <- t(pmln_table)
pmln_table <- pmln_table[-1,]
pmln_table <- as.data.frame(pmln_table)

# Create a difference column
pmln_table <- pmln_table %>%
  mutate(
    Difference = pmln_table$V2 - pmln_table$V1
)

# Rename columns and rows
colnames(pmln_table) <- c(2002, 2008, 'Difference')
rownames(pmln_table) <- c("Unvisited Districts", "Visited Districts")

print(pmln_table)
```

# Bar Chart of Vote Share PPPP
```{r, echo=False}
# Subset data for PML
pppp_bar <- df_02_08_bargraphs %>%
  filter(`Party Initials` == 'PPPP')

# Create bar chart for PML 
fig03_bargraphPPP <- ggplot(data = pppp_bar, aes(x=factor(Year), y=mean, groups=group, fill=group)) +
  geom_bar(colour='black', width=0.50, stat='identity', position=position_dodge(0.5)) + 
  geom_errorbar(aes(x=factor(Year), ymin=mean-ic, ymax=mean+ic), width=0.25, colour="#778899", alpha=1, size=1, position=position_dodge(0.5)) +
  ggtitle('Impact of CJ visits on Nuetral Opposition Party - PPP') + 
  labs(y= "Vote Share (%)", x = '', caption = str_wrap('Note: The figure presents the effect of Chief Justice visits to districts of Pakistan before 2008 elections on the share of votes in # favor of PPP party in 2008 provincial and national elections (compared to 2002 elections). The vertical lines reflect the 95% confidence intervals.')) +
  theme_light() + 
  theme(legend.position="right", legend.title=element_blank(), plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual("group", values = c("Visited" = "#2F4F4F", "Never Visited" = "#DCDCDC"))

print(fig03_bargraphPPP)
```

# Difference in Means of Vote Share PPPP
```{r, message=FALSE, echo=False}
pppp_table <- df_02_08 %>% 
  filter((Year == 2002 | 2008), `Party Initials` == 'PPPP') %>%
  group_by(Year,`Treated before 2008 elections`) %>%
  summarize(
    'Percentage of Vote Share' = mean(Vote_Share.1)
)

# Reshape the table to wide format
pppp_table <- spread(pppp_table, key = "Treated before 2008 elections", value = 'Percentage of Vote Share')

# Transpose the table, remove the first row, and save as df object
pppp_table <- t(pppp_table)
pppp_table <- pppp_table[-1,]
pppp_table <- as.data.frame(pppp_table)

# Create a difference column
pppp_table <- pppp_table %>%
  mutate(
    Difference = pppp_table$V2 - pppp_table$V1
)

# Rename columns and rows
colnames(pppp_table) <- c(2002, 2008, 'Difference')
rownames(pppp_table) <- c("Unvisited Districts", "Visited Districts")

print(pppp_table)
```

# Parallel Trend Graphs
```{r, warning=FALSE, echo=False}
# Subset data for ease of manipulation
df_subset <- df %>% select(c(Year, Vote_Share.1, 'Party Initials', treated))

# Rename for clarity
df_subset <- df_subset %>%
  mutate(
    treated = ifelse(treated == 1, 'Visited', 'Never Visted')
)

# Parallel Trend for PML                    
df_subset %>%
  filter((`Party Initials` == 'PML') & (Year >= 1997)) %>%
  ggplot(aes(x = Year, y = Vote_Share.1, color = treated)) +
  stat_summary(fun.y = mean, geom = 'line', size = 1.25) +
  theme_bw() +
  labs(x = "Year", y = "% of Vote Share", title = "Evolution of Vote Share - PML (Years 1997 to 2012)") +
  geom_vline(xintercept = 2007) +
  scale_color_manual('Treated', values = c("Visited" = "#2F4F4F", "Never Visited" = "#DCDCDC")) +
  theme(legend.position="bottom", legend.title=element_blank(), plot.title = element_text(hjust = 0.5))

# Parallel Trend for PML-N                   
df_subset %>%
  filter((`Party Initials` == 'PML-N') & (Year >= 1997)) %>%
  ggplot(aes(x = Year, y = Vote_Share.1, color = treated)) +
  stat_summary(fun.y = mean, geom = 'line', size = 1.25) +
  theme_bw() +
  labs(x = "Year", y = "% of Vote Share", title = "Evolution of Vote Share - PML-N (Years 1997 to 2012)") +
  geom_vline(xintercept = 2007) +
  scale_color_manual('Treated', values = c("Visited" = "#2F4F4F", "Never Visited" = "#DCDCDC")) +
  theme(legend.position="bottom", legend.title=element_blank(), plot.title = element_text(hjust = 0.5))

# Parallel Trend for PPPP                    
df_subset %>%
  filter(`Party Initials` == 'PPPP') %>%
  ggplot(aes(x = Year, y = Vote_Share.1, color = treated)) +
  stat_summary(fun.y = mean, geom = 'line', size = 1.25) +
  theme_bw() +
  labs(x = "Year", y = "% of Vote Share", title = "Evolution of Vote Share - PPP (Years 2002 to 2012)") +
  geom_vline(xintercept = 2007) +
  scale_color_manual('Treated', values = c("Visited" = "#2F4F4F", "Never Visited" = "#DCDCDC")) +
  theme(legend.position="bottom", legend.title=element_blank(), plot.title = element_text(hjust = 0.5))
```

# Event Study 
```{r, echo=False}
# Construct a variable that, for treated units, will take the value of the 
# number of years leading up to it (+3,-3). For untreated units, or treated 
# units that will be treated 3 or more years in the future,it takes the value -4
df$time_since_treatment = ifelse(!is.na(df$`1st_visit_year`) & (df$Year-df$`1st_visit_year`>=-3) & (df$Year-df$`1st_visit_year`<=3),df$Year-df$`1st_visit_year`,-4)
# For treated units, after 3 years, this variable will have the value 4
df$time_since_treatment = ifelse(!is.na(df$`1st_visit_year`) & (df$Year-df$`1st_visit_year`>3),4,df$time_since_treatment)

event_study_reg <- lm(Vote_Share.1 ~ factor(time_since_treatment) + constituency_dummy + year_dummy + count, data = df)

# cluster-robust SEs for event study
cl.cov.event <- cluster.vcov(event_study_reg, df$`PA ID`) 
cl.robust.se.event <- sqrt(diag(cl.cov.event))

table04_eventstudy <- stargazer(event_study_reg, type="text", keep=c("Constant","time_since_treatment"), se = list(cl.robust.se.event), dep.var.caption = '', notes = c("Robust standard errors appear in brackets (clustered at the district level)."), notes.align = "l", keep.stat=c('n', 'adj.rsq', 'f'))
```

```{r, echo=False}
# Store the beta coefficients as X and Y pairs for plotting 
summary <- as.data.frame(event_study_reg$coefficients)
y <- as.data.frame(summary[2:4,])
x <- as.data.frame(c(-1, 0, 1))

# Generate CI at 95% level for time_since_treatment variable
cis <- confint(event_study_reg, level=0.95)
cis <- cis[2:4, ]

# Create dataframe for plotting
combined_df <- cbind(x, y, cis)

fig04_eventstudy <- ggplot(combined_df, aes(x=`c(-1, 0, 1)`, y=`summary[2:4, ]`)) +
  geom_pointrange(aes(ymin=`2.5 %`, ymax=`97.5 %`)) +
  labs(x='Time to Treatment (years)', y='Effect Size (pp of Vote Share)', title='Average Treatment Effect of CJ Visit') +
  geom_line() +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print(fig04_eventstudy)
```